# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Z7-LITE-7020/04_SDK_Demo/10_ps_lwip/ps_lwip/ps_lwip.srcs/sources_1/bd/ps_lwip/ip/ps_lwip_processing_system7_0_0/ps_lwip_processing_system7_0_0.xci
# IP: The module: 'ps_lwip_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Z7-LITE-7020/04_SDK_Demo/10_ps_lwip/ps_lwip/ps_lwip.srcs/sources_1/bd/ps_lwip/ip/ps_lwip_processing_system7_0_0/ps_lwip_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_lwip_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Z7-LITE-7020/04_SDK_Demo/10_ps_lwip/ps_lwip/ps_lwip.srcs/sources_1/bd/ps_lwip/ip/ps_lwip_processing_system7_0_0/ps_lwip_processing_system7_0_0.xci
# IP: The module: 'ps_lwip_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Z7-LITE-7020/04_SDK_Demo/10_ps_lwip/ps_lwip/ps_lwip.srcs/sources_1/bd/ps_lwip/ip/ps_lwip_processing_system7_0_0/ps_lwip_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_lwip_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
